language: node_js
node_js:
- '6'
cache: yarn
env:
  global:
  - secure: JE5+hf92vqf+/ZMQyJHlQclrlrRobdUKvkmK0WZNxw53izPq0STETwzoI9Ihn9S1J/uStNDQtp9y3aREEhEYodMQDox9TPWgrDzV6TQ7gIaA8LZ0gOJHFwX9mMEk8/lwvMmn1N5sEYfdSlomaN0npPZ2rP39jugRoBSy+M6tpZ2lgczuiSxzq/loVv6NsqvLZ5l3SVn/WGCMs9eswRczQ7jOkamckiwIOG9cFpm+0mDa6HhYWV1g8aFExr/D4jHj16cQabkdCIVKMm50A91oYOLTySws7+3vyZRN76k2JsTCxc7GdYTUk6f/zOOO4Z76+sZ6ABectfQrcgF97Q7f89/ECebULOMy2C/qi+Ji78+94EGXLlSqt9OG7W09QlhvZuci+67DVTfQyu0MUJaMz8rYIzYH5uoEqdDEGO2iyGRZv71ZN20qyyS1hN8VcaePziSJB0z1/NOfp8a7y6IRoKDOw00+jf4JarLmIMidR9/pruaGnV9Z+IHXug2pyko2+pYH6nnl5SaSN8IJ3le3HMrFXIacBhaWPGNaY38WvSNrRGO7sLJuDRP6PpgAd61XAl15AHNZVoFwcla7ddLyVyDlyqyuht/6jfBI7gLGMxGppmdslwbf8N5pLdtxx/1OgifDUj6VJFugBCX02vTaoBgikyy9YM40K1vQtLnaaRY=
  - secure: RkqZvHcH2jArULzOoTylwFh82UbCvG9sH50mikU40rU2dkppGFsXZich4wFcFTzTqzGLzt/NI8rY/uB5lkqbgW8eNtJCpLD/+QDi8jjZHUZnjOaS+8SP5mYoRGI4xsQ/I/ggSQWGB/8VxHSQQokFO0w23MMpbKLUaJAwlf5vz1qpB+/1Ub1JQndwWHLeUA2zaI88k/R8i23PWdX4fTMpIdJALKHC3jHUxHUOVJeYE/dmDK6eM/nEShkiWlDHoJCHx4H/0VikEsVCx1FPtc4E1aMzDLf+plA2frRdVLBsLNihq0Sb6osyIfsPAQcsNE56www4qRXKo0IKrBhUGajhvzRK8TEheN4zOfxywEcZUuS+PNedAgzL2BSwzWbgXfMzybDH4Nau9RMDwoFJVCwrSN58m2rEB6vUfqj4Kr5wUQ8GWNCCvvMa3xBd+vC+Im0sa+Gs6erTSzuAmD/t1HAZkH6nNPhQPRXEvl9HvWeGx4/Y2RfTxt/HJC2cWIyFakq+ubZHGKC8xnxJk+7BNnIq2iM0KOqqWcuNVxkrfKPdOpzHWdDaS9QykUZnU5B1LTh9dYlEpdAdj2Y+BFPIKVOlmJArwELB6YyD57B3KRUZAE6PajvyEFAN3yhEQ/bPICmGP1eTxIeavDUsnhJbSvwzdH6Wj1mTKKymJ8Y0jj0KNg8=

# before_script: npm run test
script: npm run build
deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
